function [idx] = findLabelledMol(movie_data, cell_ID, mol_ID, label_source)
%Helper function; this finds a specific molecule in the labelled molecule
%substruct, Oliver Pambos, 12/08/2023.
%oliver.pambos@physics.ox.ac.uk
%
%
%MATLAB FUNCTION: findLabelledMol
%AUTHOR: OLIVER JAMES PAMBOS, DEPARTMENT OF PHYSICS, UNIVERSITY OF OXFORD, UK
%CONTACT: oliver.pambos@physics.ox.ac.uk
%
%LEGAL DISCLAIMER
%THIS CODE IS INTENDED FOR USE ONLY BY INDIVIDUALS WHO HAVE RECEIVED
%EXPLICIT AUTHORIZATION FROM THE AUTHOR, OLIVER JAMES PAMBOS. ANY FORM OF
%COPYING, REDISTRIBUTION, OR UNAUTHORIZED USE OF THIS CODE, IN WHOLE OR IN
%PART, IS PROHIBITED. BY USING THIS CODE, USERS SIGNIFY THAT THEY HAVE
%READ, UNDERSTOOD, AND AGREED TO BE BOUND BY THE TERMS OF SERVICE PRESENTED
%UPON SOFTWARE LAUNCH, INCLUDING THE REQUIREMENT FOR CO-AUTHORSHIP ON ANY
%RELATED PUBLICATIONS. THIS APPLIES TO ALL LEVELS OF USE, INCLUDING PARTIAL
%USE OR MODIFICATION OF THE CODE OR ANY OF ITS EXTERNAL FUNCTIONS.
%
%USERS ARE RESPONSIBLE FOR ENSURING FULL UNDERSTANDING AND COMPLIANCE WITH
%THESE TERMS, INCLUDING OBTAINING AGREEMENT FROM THE APPROPRIATE
%PUBLICATION DECISION-MAKERS WITHIN THEIR ORGANIZATION OR INSTITUTION.
%
%NOTE: UPON PUBLIC RELEASE OF THIS SOFTWARE, THESE TERMS MAY BE SUBJECT TO
%CHANGE. HOWEVER, USERS OF THIS PRE-RELEASE VERSION ARE STILL BOUND BY THE
%CO-AUTHORSHIP AGREEMENT FOR ANY USE MADE PRIOR TO THE PUBLIC RELEASE. THE
%RELEASED VERSION WILL BE AVAILABLE FROM A DESIGNATED ONLINE REPOSITORY
%WITH POTENTIALLY DIFFERENT USAGE CONDITIONS.
%
%
%This is a frequently used code block that is easier to use in a standalone
%format. Currently hardcoded for use only with the VisuallyLabelled
%substruct pending changes to include alternate labelling methods.
%
%Inputs
%------
%movie_data     (struct)    main IVK struct, containing VisuallyLabelled molecules substruct
%cell_ID        (int)       cell ID of cell to be found
%mol_ID         (int)       molecule ID of molecule to be found
%label_source   (str)       the labelled dataset to search (e.g. manual labels, random forest labelled),
%                               "manual":   manually labelled data
%                               "RF":       labels generated by random forest classification
%
%Output
%------
%idx            (int)       index of found molecule; reverts to zero if not found
%
%Dependent functions (excluding callbacks)
%-----------------------------------------
%None
    
    idx = 0;

    switch label_source
        case "manual"
            for ii = 1:numel(movie_data.results.VisuallyLabelled.LabelledMols)
              if movie_data.results.VisuallyLabelled.LabelledMols{ii, 1}.CellID == cell_ID && ...
                 movie_data.results.VisuallyLabelled.LabelledMols{ii, 1}.MolID == mol_ID
                idx = ii;
                break;
              end
            end

        case "RF"
            for ii = 1:numel(movie_data.results.RFLabelled.LabelledMols)
              if movie_data.results.RFLabelled.LabelledMols{ii, 1}.CellID == cell_ID && ...
                 movie_data.results.RFLabelled.LabelledMols{ii, 1}.MolID == mol_ID
                idx = ii;
                break;
              end
            end

        otherwise
    end
end