function [video, error_out] = illustrateMol(movie_data, cell_ID, mol_ID, play_video, save_video, video_name)
%Illustrate a molecule, Oliver Pambos, 11/11/2020.
%oliver.pambos@physics.ox.ac.uk
%
%
%MATLAB FUNCTION: illustrateMol
%AUTHOR: OLIVER JAMES PAMBOS, DEPARTMENT OF PHYSICS, UNIVERSITY OF OXFORD, UK
%CONTACT: oliver.pambos@physics.ox.ac.uk
%
%LEGAL DISCLAIMER
%THIS CODE IS INTENDED FOR USE ONLY BY INDIVIDUALS WHO HAVE RECEIVED
%EXPLICIT AUTHORIZATION FROM THE AUTHOR, OLIVER JAMES PAMBOS. ANY FORM OF
%COPYING, REDISTRIBUTION, OR UNAUTHORIZED USE OF THIS CODE, IN WHOLE OR IN
%PART, IS PROHIBITED. BY USING THIS CODE, USERS SIGNIFY THAT THEY HAVE
%READ, UNDERSTOOD, AND AGREED TO BE BOUND BY THE TERMS OF SERVICE PRESENTED
%UPON SOFTWARE LAUNCH, INCLUDING THE REQUIREMENT FOR CO-AUTHORSHIP ON ANY
%RELATED PUBLICATIONS. THIS APPLIES TO ALL LEVELS OF USE, INCLUDING PARTIAL
%USE OR MODIFICATION OF THE CODE OR ANY OF ITS EXTERNAL FUNCTIONS.
%
%USERS ARE RESPONSIBLE FOR ENSURING FULL UNDERSTANDING AND COMPLIANCE WITH
%THESE TERMS, INCLUDING OBTAINING AGREEMENT FROM THE APPROPRIATE
%PUBLICATION DECISION-MAKERS WITHIN THEIR ORGANIZATION OR INSTITUTION.
%
%NOTE: UPON PUBLIC RELEASE OF THIS SOFTWARE, THESE TERMS MAY BE SUBJECT TO
%CHANGE. HOWEVER, USERS OF THIS PRE-RELEASE VERSION ARE STILL BOUND BY THE
%CO-AUTHORSHIP AGREEMENT FOR ANY USE MADE PRIOR TO THE PUBLIC RELEASE. THE
%RELEASED VERSION WILL BE AVAILABLE FROM A DESIGNATED ONLINE REPOSITORY
%WITH POTENTIALLY DIFFERENT USAGE CONDITIONS.
%
%
%This function is also called by repopulateEventLabeller to store the
%current cropped molecule video in app.movie_data.current_video which
%enables the event labeller to more rapidly display video frames.
%
%I have not passed app GUI handles to this function so that it can be used
%on save files independently, this neccessitated the introduction of an
%error output as the app.textout field is inaccessible from this scope.
%
%Inputs
%------
%movie_data     (struct)    main data struct for eventKinetics platform
%cell_ID        (int)       cell number
%mol_ID         (int)       molecule number (track number)
%draw_track     (bool)      1 or 0 depending on whether to draw molecule track over video
%play_video     (int)       1 or 0 depending on whether to play the video externally (requires a suitable animated GIF viewer)
%save_video     (int)       1 or 0 depending on whether to save the video to disk
%video_name     (str)       a name generated by the user for the video; this is used to generate a folder name to house the video and data
%
%Ouput
%-----
%video          (mat)       matrix containing cropped video data for the specified molecule
%error_out      (str)       error output
%
%Dependent functions (excluding callbacks)
%-----------------------------------------
%findFrame()
%extractVideo()
%saveMolVideo()
    
    %append cell and mol IDs to video name, and handle scenario of user forgetting to enter a video name
    if exist('video_name', 'var')
        video_name = string(video_name) + "_C" + num2str(cell_ID) + "_M" + num2str(mol_ID);
    else
        video_name = "unnamed_video_C" + num2str(cell_ID) + "_M" + num2str(mol_ID);
    end
    
    %obtain track; obtain video frame and spatial limits
    track    = movie_data.cellROI_data(cell_ID).tracks(movie_data.cellROI_data(cell_ID).tracks(:,4)==mol_ID,:);
    frame_lo = min(track(:,3));
    frame_hi = max(track(:,3));
    x_lo     = floor(min(movie_data.cellROI_data(cell_ID).ROIVertices(:,1)) - movie_data.params.ill_border);
    x_hi     = ceil(max(movie_data.cellROI_data(cell_ID).ROIVertices(:,1)) + movie_data.params.ill_border);
    y_lo     = floor(min(movie_data.cellROI_data(cell_ID).ROIVertices(:,2)) - movie_data.params.ill_border);
    y_hi     = ceil(max(movie_data.cellROI_data(cell_ID).ROIVertices(:,2)) + movie_data.params.ill_border);
    
    if x_lo < 1
        x_lo = 1;
    end
    if y_lo < 1
        y_lo = 1;
    end
    if x_hi > movie_data.params.FOV(2)      %I am blindly assuming here that FOV has order (y, x) not (x, y) - current test dataset is square
        x_hi = movie_data.params.FOV(2);
    end
    if y_hi > movie_data.params.FOV(1)
        y_hi = movie_data.params.FOV(1);
    end
    
    %find file region to extract
    [idx_file_lo, file_frame_lo] = findFrame(movie_data.params.frame_offsets, frame_lo);
    [idx_file_hi, file_frame_hi] = findFrame(movie_data.params.frame_offsets, frame_hi);
    
    %This is required to handle the filename depending on whether it is a char array (if there is a single file), or a cell array of char arrays (if there are multiple files)
    if ischar(movie_data.params.ffFile)
        temp_filename_lo = movie_data.params.ffFile;
        temp_filename_hi = movie_data.params.ffFile;
    else
        temp_filename_lo = movie_data.params.ffFile(idx_file_lo);
        temp_filename_hi = movie_data.params.ffFile(idx_file_hi);
    end
    
    if idx_file_lo == idx_file_hi           %track is all within one video file
        video = extractVideo(movie_data.params.ffPath, temp_filename_lo, file_frame_lo, file_frame_hi, x_lo, x_hi, y_lo, y_hi);
    elseif idx_file_hi == idx_file_lo + 1   %track spans two video files
        video = extractVideo(movie_data.params.ffPath, temp_filename_lo, file_frame_lo, movie_data.params.frames_per_file(idx_file_lo), x_lo, x_hi, y_lo, y_hi);
        video = cat(3, video, extractVideo(movie_data.params.ffPath, temp_filename_hi, 1, file_frame_hi, x_lo, x_hi, y_lo, y_hi));
    elseif idx_file_hi > idx_file_lo + 1
        error_out = "Error in illustrateMol: track spans more than two files, currently unsupported as there is no currently sample data to validate";
    else
        error_out = "Unknown error in illustrateMol";
    end
    
    %resize the video and apply user settings for dynamic range adjustment
    video = imresize(video, movie_data.params.video_upscaling_factor, 'nearest');
    if strcmp(movie_data.params.dr_auto, 'Manual')
        video = mat2gray(video, [movie_data.params.dr_lo movie_data.params.dr_hi]);
    elseif strcmp(movie_data.params.dr_auto, 'Auto')
        video = mat2gray(video);
    else
        error_out = "Error in illustrateMol: unknown setting for parameter dr_auto";
    end
    
    %construct filename, and brightfield image overlay
    filename = strcat('Cell_', num2str(cell_ID), ' - Mol_', num2str(mol_ID), ' - duration_', num2str((track(end,3) - track(1,3))/movie_data.params.frame_rate, '%.2f'), 's.gif');
    overlay = imresize(movie_data.cellROI_data(cell_ID).overlay, movie_data.params.video_upscaling_factor, 'nearest');
    
    %obtain the video data; if requested, also save video to disk
    if save_video == 1
        if ~exist(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name), 'dir')
            mkdir(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name));
        else
            name_exist = 1;
            suffix = 1;
            while name_exist == 1
                if ~exist(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name), 'dir')
                    mkdir(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name));
                    name_exist = 0;
                else
                    %strip the numbers from the video (folder) name suffix
                    while isnum(video_name(end)) || strcmp(video_name(end),'_')
                        video_name = video_name(1:end-1);
                    end
                    suffix = suffix + 1;
                    video_name = strcat(video_name, '_', num2str(suffix));
                end
            end
        end
        
        %combine the video and if necessary its overlay, and save to disk
        video = saveMolVideo(video, movie_data.params.export_frame_rate, 'gif', fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name, filename), uint8(overlay),...
            movie_data.params.overlay_pc, 'manual', 1);
    else
        %combine the video and if necessary its overlay, do not save to disk
        video = saveMolVideo(video, movie_data.params.export_frame_rate, 'gif', fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name, filename), uint8(overlay),...
            movie_data.params.overlay_pc, 'manual', 0);
    end
    
    %play the video externally in an appropraite viewer
    if play_video == 1
        web(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name, filename));
    end
end

