function [] = drawStateDiagram(state_names, state_occupancies, transition_matrix, state_colours)
%Draw a state transition diagram, 14/11/2023.
%
%Author: Oliver J. Pambos, Department of Physics, University of Oxford, UK
%(oliver.pambos@physics.ox.ac.uk).
%
%ATTRIBUTION AND DISCLAIMER
%This code was conceived and developed by Oliver J. Pambos, and is
%distributed as part of the single-molecule track analysis software
%DeepTRACE.
%
%For citation of this work, refer to:
%
%   Pambos et al., Commun Biol (2026)
%   https://doi.org/10.1038/s42003-026-09899-y
%
%The publicly available version of DeepTRACE, including documentation and
%updates, is available at:
%
%   https://github.com/opambos/DeepTRACE
%
%For license and attribution terms, see the LICENSE and NOTICE files.
%
%Copyright 2022-2026 Oliver J. Pambos
%
%Licensed under the Apache License, Version 2.0 (the "License");
%you may not use this file except in compliance with the License.
%You may obtain a copy of the License at
%
%   http://www.apache.org/licenses/LICENSE-2.0
%
%Unless required by applicable law or agreed to in writing, software
%distributed under the License is distributed on an "AS IS" BASIS,
%WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%See the License for the specific language governing permissions and
%limitations under the License.
%
%
%DESIGN AND CONTEXT
%Matlab's state diagrams are ugly, and I can find no obvious open source
%alternative. This solves that problem.
%
%Generates circles for each state, scales the circles by the state
%occupancies, then connects each circle with a curved line, and arrow. Line
%curvature is generated by rotating individual pairs of circle centre
%coordinates to the horizontal axis, generating a temporary midpoint,
%which is offset by a 'curvature' parameter (fraction of the distance
%between points), and fitting this three point system to a polynomial of
%order 2 (quadratic) with 100 evenly spaced points. The inverse transform
%is then applied to the fitted points. For each connecting line individual
%points are coloured by linear interpolation through the colour space
%between the colours of the two states they connect. A triangle is
%generated at the origin, rotated to match the tangent of the midpoint of
%the curve and then coloured by the midpoint of the colour range of the two
%states in order to blend seemlessly into the arrow, this indicates the
%direction of the state transition. State labels and transition rates are
%overlaid on the figure, with rate labels offset from the coordinates of
%the cooresponding triangle/arrow.
%
%Much of this code was repurposed from my earlier unpublished
%ClusterTracker code from early 2018.
%
%Advice for exporting figures produced by this code to Inkscape
%   1. in the matlab figure window click File > Preferences, select
%       'Figure copy template' from the menu on the left, then 'Copy
%       Options', and then under 'Clipboard format' select 'Metafile',
%       click 'OK', and then click Edit > Copy Figure.
%   2. open Inkscape and paste in the image, with with imported figure
%       selected, navigate to the 'Fill and Stroke' panel (shortcut:
%       control+shift+F on Windows, or cmd+shift+F on Mac), and select the
%       Cap style 'Round Cap'. The figure can now be freely edited in
%       vector format for publication.
%
%Inputs
%------
%state_names        (cell)  the names of each state in the system
%                               example for five state: state_names =
%                               {'Bound'; 'Mobile'; 'Fast'; 'Free';
%                               'Unknown'};
%state_occupancies  (vec)   column vector of floats containing the total
%                               time spent in each state; these determine
%                               the areas of the state circles in the
%                               diagram example for five states:
%                               state_occupancies = [4810; 3150; 8102; 6923; 5123];
%transition_matrix  (mat)   NxN matrix of the transition rates to and from
%                               each state; these are used for labels next
%                               to each line; the leading diagonal is
%                               zeros; all missing transitions should be
%                               set to zero example for five state:
%                                   transition_matrix = [0,0.1,0.3,0.2,0.5; 0.3,0,0.2,0.5,0.8; 0.5,0.2,0,0.7,0.1; 0.2,0.4,0.1,0,0.4; 0.1,0.5,0.3,0.4,0];
%state_colours      (mat)   Nx3 matrix of RGB values that represent the
%                                   colours of each of N states example for
%                                   five states:
%                                       state_colours = [1,0,0; 0,0,1; 0,1,0; 0.5,0.5,0.5; 0,0,0];
%                                   for a non-coloured diagram set the
%                                   input of state_colours to be
%                                   zeros(N,3), where N is the number of
%                                   states
%
%Output
%------
%None
%
%Dependent functions (excluding callbacks)
%-----------------------------------------
%rotate2D()
%genTransitionLine()    - local to this .m file
%positionTri()          - local to this .m file
    
    %define style of curved lines and arrows
    curvature = 0.1;
    arr_len = 0.5; arr_wid = 0.5;
    
    %number of points in the gradient transition region of each line
    N_gradient_points = 60;
    
    %normalize areas to get radii (areas are proxy for state_occupancies)
    max_area = max(state_occupancies);
    scale_factor = sqrt(max_area/pi);
    radii = sqrt(state_occupancies/pi) / scale_factor;
    
    %params for invisible circle
    N = length(state_occupancies);  %number of states
    R = 5 * max(radii);             %radius of larger invisible template circle
    
    %set up figure
    h_fig = figure('MenuBar', 'none');
    h_ax = gca;
    hold on;
    axis equal;
    axis off;
    h_ax.Position = [0.05 0.05 0.9 0.9];  %shrink whitespace around plotting area
    xlim(h_ax, [-R-max(radii)*1.1, R+max(radii)]*1.1);
    ylim(h_ax, [-R-max(radii)*1.1, R+max(radii)]*1.1);
    title("State transition diagram for all states");
    set(h_fig,'Color','w');
    axis off;
    set(h_fig, 'Position', [100, 100, 700, 600]);
    
    %angle between each circle
    angular_spacing = 2 * pi / N;
    
    %preallocate positions of circles
    circle_centres = zeros(N, 2);
    
    %plot circles and labels
    for ii = 1:N
        %compute positions of state circles
        circle_centres(ii,1:2) = [R * cos(angular_spacing * (ii - 1)), R * sin(angular_spacing * (ii - 1))];
    end
    
    %loop over all non-zero elements in the transition matrix, building the matrix
    for ii = 1:size(transition_matrix, 1)
        for jj = 1:size(transition_matrix, 2)
            if transition_matrix(ii,jj) ~= 0
                %coords = circle_centres(ii:ii+1, :);
                coords(1,:) = circle_centres(ii,:);
                coords(2,:) = circle_centres(jj,:);
                
                %generate gradient colors (middle portion of line)
                colours = [linspace(state_colours(ii, 1), state_colours(jj, 1), N_gradient_points)', ...
                                  linspace(state_colours(ii, 2), state_colours(jj, 2), N_gradient_points)', ...
                                  linspace(state_colours(ii, 3), state_colours(jj, 3), N_gradient_points)'];
                
                %combine sandwich of solid colour regions at ends and gradient in middle
                colours = [repmat(state_colours(ii, :), 20, 1); ...
                          colours; ...
                          repmat(state_colours(jj, :), 20, 1)];
                
                %generate the curved line and render it
                [line_points, midpoint, theta] = genTransitionLine(coords, curvature);
                for kk = 1:size(line_points,1) - 1
                    plot(h_ax, line_points(kk:kk+1,1), line_points(kk:kk+1,2), 'k', 'LineWidth', 2, 'Color', colours(kk,:));
                end
                
                %generate triangle, and render it
                tri = positionTri(arr_len, arr_wid, midpoint, theta);
                mid_colour = (state_colours(ii,:) + state_colours(jj,:)) / 2;
                fill(h_ax, tri(:, 1), tri(:, 2), mid_colour, 'EdgeColor', 'none');

                %calculate label offset perpendicular to arrow (in left direction)
                label_offset = 0.7;
                offset_angle = theta + 90;
                dx = cosd(offset_angle);
                dy = sind(offset_angle);
                label_pos = midpoint + label_offset * [dx, dy];
                
                %format label's string containing rate
                curr_rate = transition_matrix(ii,jj);
                if curr_rate < 0.01 || curr_rate >= 1000
                    rate_str = sprintf('%.2e', curr_rate);
                    rate_str = strrep(rate_str, 'e', '×10^{');
                    rate_str = [rate_str, '} Hz'];
                else
                    rate_str = sprintf('%.2f Hz', curr_rate);
                end
                
                %plot the label displaying transition rate
                text(label_pos(1), label_pos(2), rate_str, 'FontSize', 14, 'Color', mid_colour, 'HorizontalAlignment', 'center', 'Interpreter', 'tex');
            end
        end
    end
    
    %draw the circles and labels
    for ii = 1:size(circle_centres, 1)
        rectangle(h_ax, 'Position', [circle_centres(ii,1)-radii(ii), circle_centres(ii,2)-radii(ii), 2*radii(ii), 2*radii(ii)], 'Curvature', [1, 1], 'FaceColor', [1 1 1], 'EdgeColor', state_colours(ii,:), 'LineWidth', 2);
        text(circle_centres(ii, 1), circle_centres(ii, 2), state_names{ii}, 'HorizontalAlignment', 'center', 'FontSize', 16, 'Color', state_colours(ii,:));
    end
end


function [line_points, midpoint, theta] = genTransitionLine(coords, midpoint_offset)
%Generate the points of a curved line between two state circles,
%14/11/2023.
%
%Author: Oliver J. Pambos, Department of Physics, University of Oxford, UK
%(oliver.pambos@physics.ox.ac.uk).
%
%ATTRIBUTION AND DISCLAIMER
%This code was conceived and developed by Oliver J. Pambos, and is
%distributed as part of the single-molecule track analysis software
%DeepTRACE.
%
%For citation of this work, refer to:
%
%   Pambos et al., Commun Biol (2026)
%   https://doi.org/10.1038/s42003-026-09899-y
%
%The publicly available version of DeepTRACE, including documentation and
%updates, is available at:
%
%   https://github.com/opambos/DeepTRACE
%
%For license and attribution terms, see the LICENSE and NOTICE files.
%
%Copyright 2022-2026 Oliver J. Pambos
%
%Licensed under the Apache License, Version 2.0 (the "License");
%you may not use this file except in compliance with the License.
%You may obtain a copy of the License at
%
%   http://www.apache.org/licenses/LICENSE-2.0
%
%Unless required by applicable law or agreed to in writing, software
%distributed under the License is distributed on an "AS IS" BASIS,
%WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%See the License for the specific language governing permissions and
%limitations under the License.
%
%
%DESIGN AND CONTEXT
%This takes the coordinates of two points, rotates them to horizontal,
%generates a midpoint, which is offset, applies a polyfit of order 2
%(quadratic) to generate 100 points on a curved line, and then rotates
%these points such that the end points of the lines match the original two
%points. The function also rotates the mid point, and returns this and theta
%so that the function calling this can place an arrowhead at this point.
%
%Input
%-----
%coords             (mat)       2x2 matrix of (x,y) coordinates, which are
%                                   the centres of two state circles
%midpoint_offset    (float)     offset of midpoint relative to the distance
%                                   between circle centres, larger here is
%                                   higher curvature,
%                                       0:  no curvature
%                                       1:  a semi circle
%                                       >1: higher than circular curvature
%                                       0.1 - 0.2: optimum
%
%Output
%------
%line               (mat)       100x2 matrix containing (x,y) coordinates
%                                   for 100 points defining the curved line
%                                   between two points
%midpoint           (vec)       row vector containing the coordinates of the midpoint
%theta              (float)     angle between line connecting the original two points
%
%Dependent functions (excluding callbacks)
%-----------------------------------------
%rotate2D()
    
    %calculate angle of rotation to horizontal, and rotate the points
    theta = atan2d(coords(2,2) - coords(1,2), coords(2,1) - coords(1,1));
    coords = rotate2D(coords, -theta);
    
    %compute and translate midpoint
    midpoint = mean(coords(1:2, :), 1);
    distance = norm(coords(2,:) - coords(1,:));
    midpoint(2) = midpoint(2) + midpoint_offset * distance;
    
    %generate curved line as quadratic fit to the three points
    x_vals = linspace(coords(1,1), coords(2,1), 100);
    points_for_fit = [coords(1:2,:); midpoint];
    p = polyfit(points_for_fit(:,1), points_for_fit(:,2), 2);
    y_vals = polyval(p, x_vals);
    line_points = [x_vals', y_vals'];
    
    %rotate points back to match original location
    line_points = rotate2D(line_points, theta);
    midpoint    = rotate2D(midpoint, theta);    
end


function [tri] = positionTri(arr_len, arr_wid, midpoint, theta)
%Position triangle at midpoint of curved line, 14/11/2023.
%
%Author: Oliver J. Pambos, Department of Physics, University of Oxford, UK
%(oliver.pambos@physics.ox.ac.uk).
%
%ATTRIBUTION AND DISCLAIMER
%This code was conceived and developed by Oliver J. Pambos, and is
%distributed as part of the single-molecule track analysis software
%DeepTRACE.
%
%For citation of this work, refer to:
%
%   Pambos et al., Commun Biol (2026)
%   https://doi.org/10.1038/s42003-026-09899-y
%
%The publicly available version of DeepTRACE, including documentation and
%updates, is available at:
%
%   https://github.com/opambos/DeepTRACE
%
%For license and attribution terms, see the LICENSE and NOTICE files.
%
%Copyright 2022-2026 Oliver J. Pambos
%
%Licensed under the Apache License, Version 2.0 (the "License");
%you may not use this file except in compliance with the License.
%You may obtain a copy of the License at
%
%   http://www.apache.org/licenses/LICENSE-2.0
%
%Unless required by applicable law or agreed to in writing, software
%distributed under the License is distributed on an "AS IS" BASIS,
%WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%See the License for the specific language governing permissions and
%limitations under the License.
%
%
%DESIGN AND CONTEXT
%
%Inputs
%------
%arr_len    (float)     arrow length
%arr_wid    (float)     arrow width
%midpoint   (float)     midpoint of line
%theta      (float)     angle of arrow
%
%Output
%------
%tri        (mat)       3x2 matrix of (x,y) coordinates of triangle points
%
%Dependent functions (excluding callbacks)
%-----------------------------------------
%rotate2D()

        %generate a virtual triangle around (0, 0)
        tri(1, :) = [-arr_wid/2 -arr_len/2];
        tri(2, :) = [0          arr_len/2];
        tri(3, :) = [arr_wid/2  -arr_len/2];
        
        tri = rotate2D(tri, theta - 90);
        
        %move triangle to mid-point of line
        tri(:, 1) = tri(:, 1) + midpoint(1);
        tri(:, 2) = tri(:, 2) + midpoint(2);
end

