function [idx] = findLabelledMol(movie_data, cell_ID, mol_ID, label_source)
%Helper function; this finds a specific molecule in the labelled molecule
%substruct, Oliver Pambos, 12/08/2023.
%
%AUTHOR: OLIVER JAMES PAMBOS, DEPARTMENT OF PHYSICS, UNIVERSITY OF OXFORD
%CONTACT: oliver.pambos@physics.ox.ac.uk
%
%ATTRIBUTION AND DISCLAIMER
%This code was conceived and developed entirely by Oliver James Pambos, and
%is distributed as part of DeepTRACE.
%
%If this code contributes to results presented in a scientific publication,
%the following article should be cited:
%
%   https://doi.org/10.1101/2025.05.15.654348
%
%The publicly available version of DeepTRACE, including documentation and
%updates, is available at:
%
%   https://github.com/opambos/DeepTRACE
%
%For full license, attribution, and citation terms, see the LICENSE and
%NOTICE files distributed with DeepTRACE.
%
%Copyright 2022-2026 Oliver James Pambos
%
%Licensed under the Apache License, Version 2.0 (the "License");
%you may not use this file except in compliance with the License.
%You may obtain a copy of the License at
%
%   http://www.apache.org/licenses/LICENSE-2.0
%
%Unless required by applicable law or agreed to in writing, software
%distributed under the License is distributed on an "AS IS" BASIS,
%WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%See the License for the specific language governing permissions and
%limitations under the License.
%
%
%DESIGN AND CONTEXT
%This is a frequently used code block that is easier to use in a standalone
%format. Currently hardcoded for use only with the VisuallyLabelled
%substruct pending changes to include alternate labelling methods.
%
%Inputs
%------
%movie_data     (struct)    main IVK struct, containing VisuallyLabelled molecules substruct
%cell_ID        (int)       cell ID of cell to be found
%mol_ID         (int)       molecule ID of molecule to be found
%label_source   (str)       the labelled dataset to search (e.g. manual labels, random forest labelled),
%                               "manual":   manually labelled data
%                               "RF":       labels generated by random forest classification
%
%Output
%------
%idx            (int)       index of found molecule; reverts to zero if not found
%
%Dependent functions (excluding callbacks)
%-----------------------------------------
%None
    
    idx = 0;

    switch label_source
        case "manual"
            for ii = 1:numel(movie_data.results.VisuallyLabelled.LabelledMols)
              if movie_data.results.VisuallyLabelled.LabelledMols{ii, 1}.CellID == cell_ID && ...
                 movie_data.results.VisuallyLabelled.LabelledMols{ii, 1}.MolID == mol_ID
                idx = ii;
                break;
              end
            end

        case "RF"
            for ii = 1:numel(movie_data.results.RFLabelled.LabelledMols)
              if movie_data.results.RFLabelled.LabelledMols{ii, 1}.CellID == cell_ID && ...
                 movie_data.results.RFLabelled.LabelledMols{ii, 1}.MolID == mol_ID
                idx = ii;
                break;
              end
            end

        otherwise
    end
end