function [video, error_out] = illustrateMol(movie_data, cell_ID, mol_ID, play_video, save_video, video_name, upscale_factor, flipped)
%Illustrate a molecule, 11/11/2020.
%
%Author: Oliver J. Pambos, Department of Physics, University of Oxford, UK
%(oliver.pambos@physics.ox.ac.uk).
%
%ATTRIBUTION AND DISCLAIMER
%This code was conceived and developed by Oliver J. Pambos, and is
%distributed as part of the single-molecule track analysis software
%DeepTRACE.
%
%For citation of this work, refer to:
%
%   Pambos et al., Commun Biol (2026)
%   https://doi.org/10.1038/s42003-026-09899-y
%
%The publicly available version of DeepTRACE, including documentation and
%updates, is available at:
%
%   https://github.com/opambos/DeepTRACE
%
%For license and attribution terms, see the LICENSE and NOTICE files.
%
%Copyright 2022-2026 Oliver J. Pambos
%
%Licensed under the Apache License, Version 2.0 (the "License");
%you may not use this file except in compliance with the License.
%You may obtain a copy of the License at
%
%   http://www.apache.org/licenses/LICENSE-2.0
%
%Unless required by applicable law or agreed to in writing, software
%distributed under the License is distributed on an "AS IS" BASIS,
%WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%See the License for the specific language governing permissions and
%limitations under the License.
%
%
%DESIGN AND CONTEXT
%This function is also called by repopulateEventLabeller to store the
%current cropped molecule video in app.movie_data.current_video which
%enables the human annotation system to more rapidly display video frames.
%
%I have not passed app GUI handles to this function so that it can be used
%on save files independently, this neccessitated the introduction of an
%error output as the app.textout field is inaccessible from this scope.
%
%Inputs
%------
%movie_data     (struct)    main data struct for eventKinetics platform
%cell_ID        (int)       cell number
%mol_ID         (int)       molecule number (track number)
%draw_track     (bool)      1 or 0 depending on whether to draw molecule
%                               track over video
%play_video     (int)       1 or 0 depending on whether to play the video
%                               externally (requires a suitable animated
%                               GIF viewer)
%save_video     (int)       1 or 0 depending on whether to save the video
%                               to disk
%video_name     (str)       a name generated by the user for the video;
%                               this is used to generate a folder name to
%                               house the video and data
%upscale_factor (int)       upscaling factor for video output; the factor
%                               indicates the increase length and height of
%                               the output video
%flipped        (bool)      true if the reference video and meshes were
%                               flipped during data import (requires
%                               subsequent flipping of raw fluroescence
%                               video)
%
%Ouput
%-----
%video          (mat)       matrix containing cropped video data for the
%                               specified molecule
%error_out      (str)       error output
%
%Dependent functions (excluding callbacks)
%-----------------------------------------
%findFrame()
%extractVideo()
%saveMolVideo()
    
    %append cell and mol IDs to video name, and handle scenario of user forgetting to enter a video name
    if exist('video_name', 'var')
        video_name = string(video_name) + "_C" + num2str(cell_ID) + "_M" + num2str(mol_ID);
    else
        video_name = "unnamed_video_C" + num2str(cell_ID) + "_M" + num2str(mol_ID);
    end
    
    %obtain track; obtain video frame and spatial limits
    track    = movie_data.cellROI_data(cell_ID).tracks(movie_data.cellROI_data(cell_ID).tracks(:,4)==mol_ID,:);
    frame_lo = min(track(:,3));
    frame_hi = max(track(:,3));
    x_lo     = floor(min(movie_data.cellROI_data(cell_ID).ROIVertices(:,1)) - movie_data.params.ill_border);
    x_hi     = ceil(max(movie_data.cellROI_data(cell_ID).ROIVertices(:,1)) + movie_data.params.ill_border);
    y_lo     = floor(min(movie_data.cellROI_data(cell_ID).ROIVertices(:,2)) - movie_data.params.ill_border);
    y_hi     = ceil(max(movie_data.cellROI_data(cell_ID).ROIVertices(:,2)) + movie_data.params.ill_border);
    
    if x_lo < 1
        x_lo = 1;
    end
    if y_lo < 1
        y_lo = 1;
    end
    if x_hi > movie_data.params.FOV(2)      %I am blindly assuming here that FOV has order (y, x) not (x, y) - current test dataset is square
        x_hi = movie_data.params.FOV(2);
    end
    if y_hi > movie_data.params.FOV(1)
        y_hi = movie_data.params.FOV(1);
    end
    
    %find file region to extract
    [idx_file_lo, file_frame_lo] = findFrame(movie_data.params.frame_offsets, frame_lo);
    [idx_file_hi, file_frame_hi] = findFrame(movie_data.params.frame_offsets, frame_hi);
    
    %This is required to handle the filename depending on whether it is a char array (if there is a single file), or a cell array of char arrays (if there are multiple files)
    if ischar(movie_data.params.ffFile)
        temp_filename_lo = movie_data.params.ffFile;
        temp_filename_hi = movie_data.params.ffFile;
    else
        temp_filename_lo = movie_data.params.ffFile(idx_file_lo);
        temp_filename_hi = movie_data.params.ffFile(idx_file_hi);
    end
    
    %adjust cropped region to mirror image if user flipped reference video and meshes during data import
    if flipped
        %reassign y_lo and y_hi
        image_height = size(movie_data.brightfield_image, 1);
        
        new_y_lo = image_height - y_hi + 1;
        new_y_hi = image_height - y_lo + 1;
        y_lo = new_y_lo;
        y_hi = new_y_hi;
    end
    
    if idx_file_lo == idx_file_hi           %track is all within one video file
        video = extractVideo(movie_data.params.ffPath, temp_filename_lo, file_frame_lo, file_frame_hi, x_lo, x_hi, y_lo, y_hi);
    elseif idx_file_hi == idx_file_lo + 1   %track spans two video files
        video = extractVideo(movie_data.params.ffPath, temp_filename_lo, file_frame_lo, movie_data.params.frames_per_file(idx_file_lo), x_lo, x_hi, y_lo, y_hi);
        video = cat(3, video, extractVideo(movie_data.params.ffPath, temp_filename_hi, 1, file_frame_hi, x_lo, x_hi, y_lo, y_hi));
    elseif idx_file_hi > idx_file_lo + 1
        error_out = "Error in illustrateMol: track spans more than two files, currently unsupported as there is no currently sample data to validate";
    else
        error_out = "Unknown error in illustrateMol";
    end
    
    %if user flipped video on data import, also flip cropped video
    if flipped
        video = flipud(video);
    end
    
    %resize the video and apply user settings for dynamic range adjustment
    if upscale_factor ~= 1
        video = imresize(video, upscale_factor, 'nearest');
    end
    if strcmp(movie_data.params.dr_auto, 'Manual')
        video = mat2gray(video, [movie_data.params.dr_lo movie_data.params.dr_hi]);
    elseif strcmp(movie_data.params.dr_auto, 'Auto')
        video = mat2gray(video);
    else
        error_out = "Error in illustrateMol: unknown setting for parameter dr_auto";
    end
    
    %construct filename, and brightfield image overlay
    filename = strcat('Cell_', num2str(cell_ID), ' - Mol_', num2str(mol_ID), ' - duration_', num2str((track(end,3) - track(1,3))/movie_data.params.frame_rate, '%.2f'), 's.gif');
    if upscale_factor == 1
        overlay = movie_data.cellROI_data(cell_ID).overlay;
    else
        overlay = imresize(movie_data.cellROI_data(cell_ID).overlay, upscale_factor, 'nearest');
    end
    
    %obtain the video data; if requested, also save video to disk
    if save_video == 1
        if ~exist(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name), 'dir')
            mkdir(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name));
        else
            name_exist = 1;
            suffix = 1;
            while name_exist == 1
                if ~exist(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name), 'dir')
                    mkdir(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name));
                    name_exist = 0;
                else
                    %strip the numbers from the video (folder) name suffix
                    while isnum(video_name(end)) || strcmp(video_name(end),'_')
                        video_name = video_name(1:end-1);
                    end
                    suffix = suffix + 1;
                    video_name = strcat(video_name, '_', num2str(suffix));
                end
            end
        end
        
        %combine the video and if necessary its overlay, and save to disk
        video = saveMolVideo(video, movie_data.params.export_frame_rate, 'gif', fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name, filename), uint8(overlay),...
            movie_data.params.overlay_pc, 'manual', 1);
    else
        %combine the video and if necessary its overlay, do not save to disk
        video = saveMolVideo(video, movie_data.params.export_frame_rate, 'gif', fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name, filename), uint8(overlay),...
            movie_data.params.overlay_pc, 'manual', 0);
    end
    
    %play the video externally in an appropraite viewer
    if play_video == 1
        web(fullfile(movie_data.params.ffPath, 'Saved molecule videos', video_name, filename));
    end
end